In [1]:
import numpy as np

In [4]:
#サンプルデータの全結合層による変換

#重み
w1 = np.random.randn(2, 4)
#バイアス（broadcastで(10, 4)に）
b1 = np.random.randn(4)
#入力
x = np.random.randn(10, 2)
h = np.dot(x, w1) + b1
h

array([[-1.83133675, -2.46958429,  0.77176088, -0.20767345],
       [-4.37467278, -1.2486783 ,  1.18646318, -1.77192196],
       [ 1.55237094, -2.11543189,  0.05737451,  2.47920989],
       [ 0.41207075, -1.02394036,  0.19857296,  1.94447615],
       [-3.58553543, -1.10702107,  1.01500051, -1.12721166],
       [ 1.31130851, -0.0781225 , -0.06130043,  2.91930528],
       [ 0.99484506, -0.55226948,  0.04177134,  2.53297855],
       [-3.45185501, -1.21352628,  0.99668369, -1.05795479],
       [ 0.21067994, -0.87908581,  0.22744968,  1.83536461],
       [ 0.40698035, -0.80094626,  0.18127067,  2.00887416]])

In [7]:
#sigmoid func
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

a = sigmoid(h)
a

array([[0.1380791 , 0.07801813, 0.68390169, 0.44826743],
       [0.01243567, 0.22292901, 0.76610791, 0.14530348],
       [0.82525591, 0.10760595, 0.51433969, 0.92267144],
       [0.6015843 , 0.26426058, 0.54948076, 0.87484307],
       [0.02697405, 0.24842667, 0.73399762, 0.24467605],
       [0.78773203, 0.4804793 , 0.48467969, 0.94879256],
       [0.73004385, 0.36533803, 0.51044132, 0.92642164],
       [0.03071359, 0.22907771, 0.73040605, 0.25770049],
       [0.55247603, 0.29336726, 0.55661854, 0.86239957],
       [0.6003636 , 0.30982314, 0.54519398, 0.88172566]])

In [10]:
#入力2, 隠れ層4, 出力3の2層のNN
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.random.randn(10, 2)
w1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
w2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

#1層目
h = np.dot(x, w1) + b1
#活性化関数で非線形なこうか
a = sigmoid(h)
#2層目
s = np.dot(a, w2) + b2
s

#→3クラス分類が可能

array([[-0.98917503,  0.11644575,  1.54069764],
       [-0.8541167 ,  0.0272978 ,  1.96437305],
       [-0.9921752 ,  0.12908969,  1.51891029],
       [-0.96831838,  0.18009323,  1.55151048],
       [-0.92555815,  0.07277556,  1.79475401],
       [-0.96082528,  0.19737066,  1.53832013],
       [-1.01006753,  0.21363428,  1.35696903],
       [-0.88229161,  0.10563184,  1.81545268],
       [-0.92937193, -0.05645574,  1.89797262],
       [-0.98433816,  0.22035699,  1.43293044]])

In [11]:
### sigmoid, affineレイヤの実装
class sigmoid:
    def __init__(self) -> None:
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))
    
class affine:
    def __init__(self, W, b) -> None:
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


        

In [19]:
aff = affine(np.random.randn(2, 4), np.random.randn(4))
sig = sigmoid()
h = aff.forward(np.random.randn(10, 2))
a = sig.forward(h)
a

array([[0.71903875, 0.39917948, 0.63137393, 0.44890583],
       [0.50245349, 0.26159967, 0.3845071 , 0.65479194],
       [0.39140365, 0.29995038, 0.35654513, 0.58185955],
       [0.41516671, 0.25144435, 0.32856765, 0.66630421],
       [0.20639642, 0.2212375 , 0.19431403, 0.70283012],
       [0.08611293, 0.04393964, 0.03324068, 0.96873791],
       [0.64611981, 0.28867549, 0.49361483, 0.61928024],
       [0.57210641, 0.43808371, 0.56973718, 0.38092998],
       [0.09221711, 0.03307531, 0.02800726, 0.97953677],
       [0.14031373, 0.05889541, 0.05619197, 0.95371097]])

In [20]:
#affine and sigmoid matometa class twolayernet
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size) -> None:
        I, H, O = input_size, hidden_size, output_size
        
        #重みとバイアスの初期化
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        #レイヤの生成
        self.layers = [
            affine(W1, b1),
            sigmoid(),
            affine(W2, b2)
        ]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    


In [22]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
model.predict(x)

array([[-0.88672255,  0.38092832, -1.6032961 ],
       [ 0.55379304, -0.24550236, -1.67915387],
       [-0.85047429,  0.39714641, -1.58079351],
       [-0.22073267,  0.30212753, -1.38203107],
       [ 1.15694778, -0.30080611, -1.32320232],
       [ 1.32947863, -0.3910915 , -1.35905491],
       [ 1.24708348, -0.28281811, -1.23952498],
       [ 1.44692547, -0.34399661, -1.22947999],
       [-0.20587199,  0.19792387, -1.54093323],
       [ 0.76548073, -0.06572363, -1.21969711]])